// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaHAw6psvJMojuTf9ZraUqYhdMPY849ts',
    appId: '1:609029482385:web:a34406b888ac909a6ddc30',
    messagingSenderId: '609029482385',
    projectId: 'auth-seblak-mandji',
    authDomain: 'auth-seblak-mandji.firebaseapp.com',
    storageBucket: 'auth-seblak-mandji.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKkQVTSAd0aZDlPuv1gR8-Flkm0mWGxvk',
    appId: '1:609029482385:android:00b738faa2b201b26ddc30',
    messagingSenderId: '609029482385',
    projectId: 'auth-seblak-mandji',
    storageBucket: 'auth-seblak-mandji.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqGwvv_535tZyrhsvnlLx8sJPUDK9m4fU',
    appId: '1:609029482385:ios:7b8a9ccec4582f7d6ddc30',
    messagingSenderId: '609029482385',
    projectId: 'auth-seblak-mandji',
    storageBucket: 'auth-seblak-mandji.appspot.com',
    iosBundleId: 'com.example.seblakMandji',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqGwvv_535tZyrhsvnlLx8sJPUDK9m4fU',
    appId: '1:609029482385:ios:704ca7c875c95f666ddc30',
    messagingSenderId: '609029482385',
    projectId: 'auth-seblak-mandji',
    storageBucket: 'auth-seblak-mandji.appspot.com',
    iosBundleId: 'com.example.seblakMandji.RunnerTests',
  );
}
